const texture_dic = {
	厚い: 'thick',
	脂っこい: 'greasy',
	油っこい: 'greasy',
	脂っぽい: 'greasy',
	油っぽい: 'oily',
	粗い: 'rough',
	泡状: 'foamy',
	泡の立つ: 'foamy',
	いがいが: 'spiky',
	糸を引く: 'stringy',
	薄い: 'thin',
	うろこ状: 'scaly',
	液状: 'liquid',
	液のしたたる: 'liquid',
	重い: 'heavily',
	かくばった: 'angular',
	かさかさ: 'dry',
	がさがさ: 'chapped',
	かさつく: 'dry',
	かすかす: 'mealy',
	かたい: 'hard',
	硬い: 'hard',
	堅い: 'hard',
	固い: 'hard',
	塊状: 'massive',
	かちかち: 'hard',
	がちがち: 'solid',
	かちんかちん: 'solid',
	かちんこちん: 'solid',
	がっしり: 'massive',
	かどばった: 'angular',
	かみ切れない: 'tough',
	かみごたえ: 'tough',
	かゆ状: 'gruel',
	からから: 'dry',
	からっ: 'dry',
	からみつく: 'entangled',
	からり: 'dry',
	カリカリ: 'crisp',
	ガリガリ: 'coarse',
	カリッ: 'crisp',
	ガリッ: 'coarse',
	顆粒状: 'granular',
	軽い: 'light',
	乾いた: 'dry',
	皮ばった: 'skinned',
	キシキシ: 'powdery',
	ギシギシ: 'packed',
	ぎっしり: 'fully',
	ぎとぎと: 'greasy',
	ぎとっ: 'greasy',
	きめ細かい: 'fine',
	吸湿性: 'hygroscopicity',
	球状: 'spherical',
	吸水性: 'spongy',
	強靭な: 'tough',
	切れやすい: 'tender',
	均一な: 'uniform',
	くしゃくしゃ: 'crumpled',
	ぐしゃぐしゃ: 'crumpled',
	くしゃっ: 'crumpled',
	ぐしゃっ: 'crumpled',
	ぐずぐず: 'brittle',
	くずれやすい: 'brittle',
	くたくた: 'くたくた',
	くだけやすい: 'easy to fall',
	くたっ: 'beat away',
	口あたり: 'per mouth',
	口ざわり: 'mouth feel',
	口どけ: 'melting',
	くちゃくちゃ: 'messy',
	ぐちゃぐちゃ: 'messy',
	くちゃっ: 'chewy',
	ぐちゃっ: 'messy',
	くちゅくちゅ: 'kukyushu',
	ぐちょぐちょ: 'swarm',
	ぐちょっ: 'soap opera',
	くっつく: 'stick together',
	くにゃくにゃ: 'cloak',
	ぐにゃぐにゃ: 'squishy',
	くにゃっ: 'cute',
	ぐにゃっ: 'hanging out',
	くにゃり: 'chubby',
	ぐにゃり: 'quietly',
	くにゅくにゅ: 'kuni Kyunyuu',
	ぐにゅぐにゅ: 'gig',
	ぐにゅっ: 'gutter',
	くにょくにょ: 'hurdle',
	ぐにょぐにょ: 'tofu',
	ぐにょっ: 'tortoiseshell',
	クリーミー: 'creamy',
	クリーム状: 'creamy',
	結晶状: 'crystalline',
	コキコキ: 'koki Koki',
	こく: 'rich',
	固形: 'solid',
	こし: 'chewy',
	こちこち: 'here and there',
	こちっ: 'hard',
	こちんこちん: 'gangcha',
	ごつごつ: 'rugged',
	こってり: 'rich',
	粉状: 'powder',
	粉っぽい: 'powdery',
	粉をふいた: 'i bought powder',
	細かい: 'fine',
	ゴム: 'rubbery',
	コリコリ: 'koryikoli',
	ゴリゴリ: 'gorgori',
	コリッ: 'korit',
	ゴリッ: 'gorr',
	ころころ: 'around the corner',
	ごろごろ: 'chunky',
	ころっ: 'be ruined',
	ごろっ: 'got it',
	ころり: 'rolling',
	ごろり: 'full',
	こわい: 'scary',
	ごわごわ: 'stiff',
	ごわっ: 'end',
	こわれやすい: 'easy to break',
	サクサク: 'crunchy',
	ザクザク: 'zag',
	サクッ: 'custard',
	ザクッ: 'squeak',
	裂けやすい: 'it is easy to split',
	さっくり: 'crisp',
	ざっくり: 'crunchy',
	さらさら: 'rustling',
	ざらざら: 'rough',
	さらっ: 'scumming',
	ざらっ: 'rough',
	ざらつく: 'rough',
	さらり: 'stiffness',
	ざらり: 'rough',
	サンドイッチ状: 'sandwich',
	しけた: 'i did it.',
	しけった: 'i did it',
	しこしこ: 'awkwardly',
	しこっ: 'shriek',
	舌ざわり: 'tingling',
	舌に残る: 'remains on the tongue',
	しっかり: 'firm',
	しっけた: 'i found out',
	しっとり: 'moist',
	じっとり: 'moist',
	じとじと: 'take it easy',
	しとっ: 'moist',
	じとっ: 'a fortune',
	しなしな: 'sad story',
	しなっ: 'abnormality',
	しなびた: 'shriveled',
	しなやか: 'supple',
	渋い: 'astringent',
	しまり: 'spirit',
	湿った: 'moist',
	霜降り状: 'marbled form',
	シャーベット状: 'sherbet shaped',
	シャキシャキ: 'crisp',
	シャキッ: 'crispy',
	シャクシャク: 'shakushaku',
	しゃっきり: 'sharp',
	シャリシャリ: 'シャリシャリ',
	ジャリジャリ: 'ジャリジャリ',
	シャリッ: 'shari',
	ジャリッ: 'jari',
	ジューシー: 'juicy',
	柔軟: 'flexible',
	収れん性: 'astringency',
	じゅくじゅく: 'jyukyuku',
	じゅるじゅる: 'jr.',
	じゅるっ: 'untitled',
	シュワシュワ: 'fizzy',
	ジュワジュワ: 'juwahewa',
	シュワッ: 'schwarz',
	ジュワッ: 'juwatu',
	ショリショリ: 'shochshori',
	ショリッ: 'shori',
	汁気: 'watery',
	芯: 'core',
	しんなり: 'shine',
	すかすか: 'faint',
	すかっ: 'it is expensive',
	すじっぽい: 'sluggish',
	ずっしり: 'heavily',
	砂状: 'sandy',
	砂っぽい: 'sandy',
	すべすべ: 'smooth',
	すべる: 'to slide',
	スポンジ状: 'sponge shape',
	するする: 'to make',
	ズルズル: 'slurle',
	するっ: 'got it',
	ズルッ: 'ズルッ',
	するり: 'slide',
	ずるり: 'slack',
	ゼリー状: 'jelly like',
	繊維状: 'fibrous',
	層状: 'layered',
	たらたら: 'disappointed',
	だらだら: 'sloppy',
	たらっ: 'get ready',
	だらっ: 'trail',
	たらり: 'tangle',
	だらり: 'lovely',
	弾力: 'chewy',
	ちぎれやすい: 'easily torn',
	ちぢれた: 'broken',
	ちゅるちゅる: 'quietly',
	ちゅるっ: 'chulu',
	ちりちり: 'chilling',
	ちりっ: 'dirty',
	粒状: 'granular',
	つぶつぶ: 'grainy',
	つぶれやすい: 'easy to collapse',
	つまった: 'caught',
	つるっ: 'twist',
	つるつる: 'slippery',
	つるり: 'sling',
	つるん: 'tsuruin',
	でこぼこ: 'bumpy',
	とげとげ: 'togoshi',
	どっしり: 'heavily',
	とろける: 'melty',
	とろっ: 'mushy',
	どろっ: 'thick',
	とろとろ: 'melty',
	どろどろ: 'muddy',
	とろみ: 'temp',
	とろり: 'melth',
	どろり: 'rolling',
	なめらか: 'smooth',
	にちゃっ: 'in',
	にちゃにちゃ: 'messy',
	乳状: 'milky',
	にゅるっ: 'untitled',
	にゅるにゅる: 'northern',
	にゅるり: 'nursery',
	ぬたっ: 'muzzle',
	ぬちゃっ: 'dogs',
	ぬちゃぬちゃ: 'clauded',
	ぬとっ: 'a rooster',
	ぬめっ: 'slimy',
	ぬめぬめ: 'stuffed',
	ぬめり: 'slime',
	ぬらっ: 'nursery',
	ぬらぬら: 'slimy',
	ぬらり: 'the nerve',
	ぬるっ: 'slimy',
	ぬるぬる: 'slimy',
	ぬるり: 'tepid',
	ねたっ: 'nebuta',
	ねたねた: 'nebuta',
	ねちっ: 'nachi',
	ねちねち: 'persistent',
	ねちゃっ: 'jogging',
	ねちゃねちゃ: 'naughty',
	ねちょっ: 'roughly',
	ねちょねちょ: 'a cat',
	ねっちり: 'sticky',
	ねっとり: 'gooey',
	ねとっ: 'retail price',
	ねとつく: 'stickiness',
	ねとねと: 'bellows',
	ねばい: 'awful',
	ねばっ: 'a truck',
	ねばつく: 'staggering',
	ねばっこい: 'stubborn',
	ねばねば: 'sticky',
	ねばり: 'taste',
	濃厚: 'rich',
	のどごし: 'nodding',
	のびた: 'nobita',
	のびる: 'extend',
	糊状: 'paste shape',
	パキッ: 'awesome',
	バキッ: 'fool',
	パキパキ: 'paki Paki',
	バキバキ: 'beckoning',
	歯切れ: 'crispness',
	薄片状: 'flaky',
	歯ごたえ: 'chewy',
	ばさっ: 'stray',
	ぱさっ: 'pas',
	ぱさつく: 'topple',
	ばさばさ: 'bulk',
	ぱさぱさ: 'dry',
	歯ざわり: 'teeth',
	はじける: 'to hit',
	パチパチ: 'crackling',
	パフ状: 'puffed',
	ばらっ: 'rose',
	ぱらっ: 'ぱらっ',
	ばらばら: 'loose',
	ぱらぱら: 'ぱらぱら',
	ばらり: 'bulk',
	ぱらり: 'hurry',
	バリッ: 'bari',
	パリッ: 'crisp',
	バリバリ: 'bali Bali',
	パリパリ: 'crisp',
	ひからびた: 'plucked out',
	びちゃっ: 'soggy',
	びちゃびちゃ: 'a bitch',
	ぴちゃぴちゃ: 'chubby',
	ふかっ: 'wipe',
	ふかふか: 'fluffy',
	ぶちっ: 'petty',
	ぷちっ: 'petty',
	ぶちぶち: 'a bitch',
	ぷちぷち: 'petit Petit',
	ぶちゅ: 'bubu',
	ぷちゅ: 'pucchu',
	ふっくら: 'plump',
	ふっくり: 'plump',
	ぷっくり: 'plump',
	ぶつっ: 'crush',
	ぷつっ: 'stupid',
	ぶつぶつ: 'bumpy',
	ぷつぷつ: 'gluttonous',
	ぷにぷに: 'punipuni',
	ふにゃっ: 'faraway',
	ふにゃふにゃ: 'limp',
	ふにゃり: 'futsumi',
	ぷにゅぷにゅ: 'punyupu',
	ふにょふにょ: 'futono-cho',
	ぶにょぶにょ: 'buddhism',
	ぷにょぷにょ: "people's Pantyhose",
	ふやけた: 'soggy',
	ぶよっ: 'puffing',
	ぶよぶよ: 'pale boy',
	ぷよぷよ: 'puyo Puyo',
	ぶりっ: 'hunting',
	ぷりっ: 'purit',
	ぶりぶり: 'blunt',
	ぷりぷり: 'pretty',
	ぶりん: 'pineapple',
	ぷりん: 'ぷりん',
	ぶりんぶりん: 'sweet potato',
	ぷりんぷりん: 'purin',
	ふるふる: 'trembling',
	ぶるぶる: 'jiggly',
	ぷるぷる: 'jiggly',
	ぶるん: 'buzz',
	ぷるん: 'jiggly',
	ぶるんぶるん: 'bukkurun',
	ぷるんぷるん: 'purunpurun',
	ふわっ: 'fluffy',
	ふわふわ: 'fluffy',
	ぶわぶわ: 'trembling',
	ぷわぷわ: 'fluffy',
	ふわり: 'fluffy',
	分離: 'brittle',
	ふんわか: 'fluffy',
	ふんわり: 'fluffy',
	べたっ: 'sticky',
	ぺたっ: 'pete',
	べたつく: 'sticky',
	べたべた: 'sticky',
	ぺたぺた: 'cheap',
	べちゃっ: 'soggy',
	ぺちゃっ: 'pecha',
	べちゃべちゃ: 'soggy',
	べちゃり: 'baby',
	ぺちゃり: 'peeping',
	べちょっ: 'beautiful',
	べちょべちょ: 'bechchachocho',
	べったり: 'sticky',
	ぺったり: 'perfection',
	べっとり: 'tattily',
	ぺっとり: 'peeping',
	べとっ: 'sticky',
	ぺとっ: 'one',
	べとつく: 'sticky',
	べとべと: 'sticky',
	ぺとぺと: 'stiff',
	へなっ: 'become',
	へなへな: 'disengagement',
	ぺらぺら: 'fluent',
	べろべろ: 'licking',
	ボキッ: 'bokek',
	ポキッ: 'pokey',
	ボキボキ: 'pokémon',
	ポキポキ: 'pokipoki',
	ほくほく: 'ほくほく',
	ぽくぽく: 'warm',
	ほぐれやすい: 'easy to loosen',
	ほこほこ: 'takoyako',
	ぼそっ: 'fight',
	ぽそっ: 'powered by Translate',
	ぼそぼそ: 'rough',
	ぽそぽそ: 'absolutely',
	ほっくり: 'ほっくり',
	ぽっくり: 'peck',
	ほっこり: 'ほっこり',
	ぼってり: 'bloody',
	ぽってり: 'clumsy',
	ぼてっ: 'welcome',
	ぽてっ: 'cheap',
	ぼてぼて: 'bokutobora',
	ボリッ: 'bolt',
	ポリッ: 'poly',
	ボリボリ: 'bolivoli',
	ポリポリ: 'polypoly',
	ほろっ: 'crumbly',
	ぼろっ: 'rags',
	ぽろっ: 'burning',
	ほろほろ: 'crumbly',
	ぼろぼろ: 'tattered',
	ぽろぽろ: 'sprinkle',
	ほろり: 'rolling',
	ぼろり: 'ragged',
	ぽろり: 'huge',
	ほわっ: 'roast',
	ほわほわ: 'fluffy',
	膜状: 'filmy',
	まったり: 'gooey',
	まとわりつく: 'stick together',
	まろやか: 'mellow',
	水飴状: 'starch syrup',
	水気: 'watery',
	水っぽい: 'watery',
	みずみずしい: 'fresh',
	蜜状: 'honey-like',
	密な: 'dense',
	むちむち: 'むちむち',
	むっちり: 'chewy',
	むにゅっ: 'muuu',
	むにゅむにゅ: 'muyumyunyu',
	もさもさ: 'momoko',
	もそっ: 'too',
	もそもそ: 'もそもそ',
	もちっ: 'chewy',
	もちもち: 'chewy',
	もっさり: 'clamor',
	もったり: 'heavily',
	もっちり: 'chewy',
	もろい: 'fragile',
	もろっ: 'fragile',
	もろもろ: 'grassroots',
	やわらかい: 'soft',
	柔らかい: 'soft',
	軟らかい: 'soft',
	ゆるい: 'loose',
	わた状の: 'caterpillar',
};
module.exports = texture_dic;
